import pytest

from ricecooker.utils.utils import extract_path_ext

# Tests generated by Claude Sonnet 3.7


def test_extract_path_ext_basic_file():
    """Test basic file path extension extraction."""
    assert extract_path_ext("file.txt") == "txt"
    assert extract_path_ext("path/to/file.jpg") == "jpg"
    assert extract_path_ext("/absolute/path/to/file.pdf") == "pdf"
    assert extract_path_ext("file.PNG") == "png"  # Tests lowercase conversion


def test_extract_path_ext_windows_paths():
    """Test Windows-style file paths."""
    assert extract_path_ext("C:\\Users\\name\\file.docx") == "docx"
    assert extract_path_ext("D:\\path\\to\\file.xlsx") == "xlsx"
    assert extract_path_ext("\\\\network\\share\\file.csv") == "csv"


def test_extract_path_ext_urls():
    """Test URL path extension extraction."""
    assert extract_path_ext("http://example.com/file.json") == "json"
    assert extract_path_ext("https://domain.org/path/to/file.xml") == "xml"
    assert extract_path_ext("ftp://files.net/downloads/file.zip") == "zip"


def test_extract_path_ext_urls_with_query_params():
    """Test URLs with query parameters."""
    assert extract_path_ext("http://example.com/file.html?param=value") == "html"
    assert (
        extract_path_ext("https://api.domain.org/data.json?id=123&token=abc") == "json"
    )
    assert extract_path_ext("http://site.com/download.tar.gz?download=true") == "gz"


def test_extract_path_ext_no_extension():
    """Test paths with no extension."""
    with pytest.raises(ValueError):
        extract_path_ext("file_without_extension")

    with pytest.raises(ValueError):
        extract_path_ext("/path/to/file")

    with pytest.raises(ValueError):
        extract_path_ext("http://example.com/api/v1/resource")


def test_extract_path_ext_empty_extension():
    """Test paths with empty extension (dot at the end)."""
    with pytest.raises(ValueError):
        extract_path_ext("file.")

    with pytest.raises(ValueError):
        extract_path_ext("http://example.com/document.")


def test_extract_path_ext_default_ext():
    """Test default extension parameter."""
    assert extract_path_ext("file_without_extension", default_ext="txt") == "txt"
    assert extract_path_ext("file.", default_ext="dat") == "dat"
    assert (
        extract_path_ext("http://example.com/api/v1/resource", default_ext="json")
        == "json"
    )


def test_extract_path_ext_complex_paths():
    """Test more complex path scenarios."""
    assert extract_path_ext("file.tar.gz") == "gz"
    assert extract_path_ext("path/to/archive.tar.bz2") == "bz2"
    assert extract_path_ext("http://example.com/path/to/file.min.js") == "js"


def test_extract_path_ext_edge_cases():
    """Test edge cases."""
    # URL with hash fragment
    assert extract_path_ext("http://example.com/file.html#section") == "html"

    # URL with query and hash fragment
    assert extract_path_ext("http://example.com/file.php?id=1#top") == "php"

    # Path with multiple dots
    assert extract_path_ext("file.name.with.dots.txt") == "txt"
